#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=gpuq
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=24:00:00
####SBATCH --cpus-per-task=40
####SBATCH --ntasks-per-node=1
#SBATCH -J coords

python3 get_nucleation_coords.py >> ./data/output.txt
